[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    bblanchon/ArduinoJson